defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

# ─────────────────────────────────────────────────────────────────────────────
# 1) Common: Time & Location
# ─────────────────────────────────────────────────────────────────────────────
location:
  latitude:     56.75608   # degrees
  longitude:   -121.92940   # degrees
  elevation:      950                # meters above sea level
  timezone:     "America/Edmonton"
  date:        "2025-06-23"          # YYYY-MM-DD
  freq:         "15T"                   # e.g. "15T" = 15-minute intervals

# ─────────────────────────────────────────────────────────────────────────────
# 2) Simple - Basic Time Planner
#    (src/shadow_calculator.py)
# ─────────────────────────────────────────────────────────────────────────────
simple_time_planner:
  tree_height:              10             # meters (used when no CHM available)
  buffer_width_m:           10   # meters
  flight_window:
    max_shadow_pct: 30
  plot:
    enabled:      true
    figure_size: [12, 6]
    title:       "Shadow Coverage on ${location.date}"

# ─────────────────────────────────────────────────────────────────────────────
# 3) Orientation-Only Planner
#    (src/orientation_planner.py)
# ─────────────────────────────────────────────────────────────────────────────
orientation_planner:
  vector_path:  "file:///media/irina/My Book/Petronas/DATA/vector_data/lines_for_shadows.gpkg"
  output_field: "flight_windows"

# ─────────────────────────────────────────────────────────────────────────────
# 4) CHM + Orientation Planner
#    (src/height_and_orientation_planner.py)
# ─────────────────────────────────────────────────────────────────────────────
height_and_orientation_planner:
  segmentation:
    segment_length:        100
    vector_path:  "file:///media/irina/My Book/Petronas/DATA/vector_data/lines_for_shadows.gpkg"
    output_field: "flight_windows"
  chm:
    path:  "file:///media/irina/My Book/Petronas/DATA/FullData/CHM_may25.tif"
    segment_buffer_radius: 25