# config/config.yaml
# ------------------
# Default parameters for your shadow‐calculation run

hydra:
  run:
    # keep outputs in the working dir rather than create new Hydra output folders
    dir: .

latitude: 54.938643706057285
longitude: -110.35322727751391
elevation: 800            # meters above sea level
tree_height: 10           # height of the tree in meters
date: "2024-08-09"        # YYYY-MM-DD
timezone: "America/Edmonton"
