# config/config.yaml
# ------------------
hydra:
  run:
    dir: .

# Location & time settings
latitude: 54.938643706057285
longitude: -110.35322727751391
elevation: 800           # meters above sea level
timezone: "America/Edmonton"

date: "2025-06-21"     # YYYY-MM-DD
#freq: "h"               # pandas frequency for timestamps (use lowercase)
freq: "15T"              # 15-minute intervals

# Tree & shadow settings
tree_height: 10         # height of the tree in meters

flight_window:
  max_ns_shadow_pct:      50    # upper limit for acceptable NS shadow
  max_ew_shadow_pct:      50    # upper limit for acceptable EW shadow
  preferred_ns_shadow_pct: 30   # highlight especially good NS conditions
  preferred_ew_shadow_pct: 30   # highlight especially good EW conditions
  max_buffer_pct: 30


buffer_width_m: 10

# Plotting options
plot:
  enabled: true
  figure_size: [12, 6]
  title: "Shadow Coverage on ${date}"


vector_path: "/media/irina/My Book1/LiDea_Pilot/FLM/all_group_copy_ID.gpkg"
chm_path: "/media/irina/My Book1/LiDea_Pilot/LiDea1_nCHM10cm_2023.tif"
output_field: "flight_windows"
use_line_coords: True
segment_length:            100   # metres per segment
segment_buffer_radius:     25    # metres around each segment for CHM sampling
